version: '3'
volumes:
  dados:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=workers
    volumes:
      - dados:/var/lib/mysql
  frontend:
    image: nginx:1.13
    volumes:  
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80
  app:
    build: app/
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080
